Name: cic_research_challenge
Channels:
  - conda-forge
  - defaults
Dependencies:
  - python=3.13
   - pandas>=2.2.0
   - numpy>=1.26.30
   - matplotlib>=3.8.0
   - seaborn>=0.13.0
   - statsmodels>=0.14.0
   - scikit-learn>=1.4.0
   - folium>-0.15.0
   - branca >= 0.7.0
   - ipython>=8.20.0
   - jupyterlab>=4.0.0
   - ipykernel>=6.29.0